config/routes.rb
Rails.application.routes.draw do

get 'admin' => "admin_home#top"

  resources :exhibitions
  resources :schools
  resources :articles
  resources :maxims
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get "/" => "home#top"


end

app/models/exhibition.rb
class Exhibition < ApplicationRecord
end

app/controllers/exhibitions_controller.rb
class ExhibitionsController < ApplicationController
  before_action :set_exhibition, only: [:show, :edit, :update, :destroy]

  # GET /exhibitions
  # GET /exhibitions.json
  def index
    @exhibitions = Exhibition.all
  end

  # GET /exhibitions/1
  # GET /exhibitions/1.json
  def show
  end

  # GET /exhibitions/new
  def new
    @exhibition = Exhibition.new
  end

  # GET /exhibitions/1/edit
  def edit
  end

  # POST /exhibitions
  # POST /exhibitions.json
  def create
    @exhibition = Exhibition.new(exhibition_params)

    respond_to do |format|
      if @exhibition.save
        format.html { redirect_to @exhibition, notice: 'Exhibition was successfully created.' }
        format.json { render :show, status: :created, location: @exhibition }
      else
        format.html { render :new }
        format.json { render json: @exhibition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exhibitions/1
  # PATCH/PUT /exhibitions/1.json
  def update
    respond_to do |format|
      if @exhibition.update(exhibition_params)
        format.html { redirect_to @exhibition, notice: 'Exhibition was successfully updated.' }
        format.json { render :show, status: :ok, location: @exhibition }
      else
        format.html { render :edit }
        format.json { render json: @exhibition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exhibitions/1
  # DELETE /exhibitions/1.json
  def destroy
    @exhibition.destroy
    respond_to do |format|
      format.html { redirect_to exhibitions_url, notice: 'Exhibition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exhibition
      @exhibition = Exhibition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exhibition_params
      params.require(:exhibition).permit(:name, :place_ward, :place_name, :place_address, :station, :first_date, :last_date, :closed_date, :opening_time, :detail_text, :category_string)
    end
end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/views/exhibitions/_form.html.erb
<%= form_with(model: exhibition, local: true) do |form| %>
  <% if exhibition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exhibition.errors.count, "error") %> prohibited this exhibition from being saved:</h2>

      <ul>
      <% exhibition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :exhibition_name %>
  </div>

  <div class="field">
    <%= form.label :place_ward %>
    <%= form.text_field :place_ward, id: :exhibition_place_ward %>
  </div>

  <div class="field">
    <%= form.label :place_name %>
    <%= form.text_field :place_name, id: :exhibition_place_name %>
  </div>

  <div class="field">
    <%= form.label :place_address %>
    <%= form.text_field :place_address, id: :exhibition_place_address %>
  </div>

  <div class="field">
    <%= form.label :station %>
    <%= form.text_field :station, id: :exhibition_station %>
  </div>

  <div class="field">
    <%= form.label :first_date %>
    <%= form.date_select :first_date, id: :exhibition_first_date %>
  </div>

  <div class="field">
    <%= form.label :last_date %>
    <%= form.date_select :last_date, id: :exhibition_last_date %>
  </div>

  <div class="field">
    <%= form.label :closed_date %>
    <%= form.text_area :closed_date, id: :exhibition_closed_date %>
  </div>

  <div class="field">
    <%= form.label :opening_time %>
    <%= form.text_area :opening_time, id: :exhibition_opening_time %>
  </div>

  <div class="field">
    <%= form.label :detail_text %>
    <%= form.text_field :detail_text, id: :exhibition_detail_text %>
  </div>

  <div class="field">
    <%= form.label :category_string %>
    <%= form.text_field :category_string, id: :exhibition_category_string %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/exhibitions/edit.html.erb
<h1>Editing Exhibition</h1>

<%= render 'form', exhibition: @exhibition %>

<%= link_to 'Show', @exhibition %> |
<%= link_to 'Back', exhibitions_path %>

app/views/exhibitions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exhibitions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Place ward</th>
      <th>Place name</th>
      <th>Place address</th>
      <th>Station</th>
      <th>First date</th>
      <th>Last date</th>
      <th>Closed date</th>
      <th>Opening time</th>
      <th>Detail text</th>
      <th>Category string</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exhibitions.each do |exhibition| %>
      <tr>
        <td><%= exhibition.name %></td>
        <td><%= exhibition.place_ward %></td>
        <td><%= exhibition.place_name %></td>
        <td><%= exhibition.place_address %></td>
        <td><%= exhibition.station %></td>
        <td><%= exhibition.first_date %></td>
        <td><%= exhibition.last_date %></td>
        <td><%= exhibition.closed_date %></td>
        <td><%= exhibition.opening_time %></td>
        <td><%= exhibition.detail_text %></td>
        <td><%= exhibition.category_string %></td>
        <td><%= link_to 'Show', exhibition %></td>
        <td><%= link_to 'Edit', edit_exhibition_path(exhibition) %></td>
        <td><%= link_to 'Destroy', exhibition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exhibition', new_exhibition_path %>

app/views/exhibitions/new.html.erb
<h1>New Exhibition</h1>

<%= render 'form', exhibition: @exhibition %>

<%= link_to 'Back', exhibitions_path %>

app/views/exhibitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exhibition.name %>
</p>

<p>
  <strong>Place ward:</strong>
  <%= @exhibition.place_ward %>
</p>

<p>
  <strong>Place name:</strong>
  <%= @exhibition.place_name %>
</p>

<p>
  <strong>Place address:</strong>
  <%= @exhibition.place_address %>
</p>

<p>
  <strong>Station:</strong>
  <%= @exhibition.station %>
</p>

<p>
  <strong>First date:</strong>
  <%= @exhibition.first_date %>
</p>

<p>
  <strong>Last date:</strong>
  <%= @exhibition.last_date %>
</p>

<p>
  <strong>Closed date:</strong>
  <%= @exhibition.closed_date %>
</p>

<p>
  <strong>Opening time:</strong>
  <%= @exhibition.opening_time %>
</p>

<p>
  <strong>Detail text:</strong>
  <%= @exhibition.detail_text %>
</p>

<p>
  <strong>Category string:</strong>
  <%= @exhibition.category_string %>
</p>

<%= link_to 'Edit', edit_exhibition_path(@exhibition) %> |
<%= link_to 'Back', exhibitions_path %>