config/routes.rb
Rails.application.routes.draw do

get 'admin' => "admin_home#top"

  resources :exhibitions
  resources :schools
  resources :articles
  resources :maxims
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get "/" => "home#top"


end

app/models/maxim.rb
class Maxim < ApplicationRecord
end

app/controllers/maxims_controller.rb
class MaximsController < ApplicationController
  before_action :set_maxim, only: [:show, :edit, :update, :destroy]

  # GET /maxims
  # GET /maxims.json
  def index
    @maxims = Maxim.all
  end

  # GET /maxims/1
  # GET /maxims/1.json
  def show
  end

  # GET /maxims/new
  def new
    @maxim = Maxim.new
  end

  # GET /maxims/1/edit
  def edit
  end

  # POST /maxims
  # POST /maxims.json
  def create
    @maxim = Maxim.new(maxim_params)

    respond_to do |format|
      if @maxim.save
        format.html { redirect_to @maxim, notice: 'Maxim was successfully created.' }
        format.json { render :show, status: :created, location: @maxim }
      else
        format.html { render :new }
        format.json { render json: @maxim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maxims/1
  # PATCH/PUT /maxims/1.json
  def update
    respond_to do |format|
      if @maxim.update(maxim_params)
        format.html { redirect_to @maxim, notice: 'Maxim was successfully updated.' }
        format.json { render :show, status: :ok, location: @maxim }
      else
        format.html { render :edit }
        format.json { render json: @maxim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maxims/1
  # DELETE /maxims/1.json
  def destroy
    @maxim.destroy
    respond_to do |format|
      format.html { redirect_to maxims_url, notice: 'Maxim was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maxim
      @maxim = Maxim.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def maxim_params
      params.require(:maxim).permit(:content, :meaning, :person)
    end
end

app/helpers/maxims_helper.rb
module MaximsHelper
end

app/views/maxims/_form.html.erb
<%= form_with(model: maxim, local: true) do |form| %>
  <% if maxim.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(maxim.errors.count, "error") %> prohibited this maxim from being saved:</h2>

      <ul>
      <% maxim.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :maxim_content %>
  </div>

  <div class="field">
    <%= form.label :meaning %>
    <%= form.text_area :meaning, id: :maxim_meaning %>
  </div>

  <div class="field">
    <%= form.label :person %>
    <%= form.text_field :person, id: :maxim_person %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/maxims/edit.html.erb
<h1>Editing Maxim</h1>

<%= render 'form', maxim: @maxim %>

<%= link_to 'Show', @maxim %> |
<%= link_to 'Back', maxims_path %>

app/views/maxims/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Maxims</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Meaning</th>
      <th>Person</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maxims.each do |maxim| %>
      <tr>
        <td><%= maxim.content %></td>
        <td><%= maxim.meaning %></td>
        <td><%= maxim.person %></td>
        <td><%= link_to 'Show', maxim %></td>
        <td><%= link_to 'Edit', edit_maxim_path(maxim) %></td>
        <td><%= link_to 'Destroy', maxim, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Maxim', new_maxim_path %>

app/views/maxims/new.html.erb
<h1>New Maxim</h1>

<%= render 'form', maxim: @maxim %>

<%= link_to 'Back', maxims_path %>

app/views/maxims/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @maxim.content %>
</p>

<p>
  <strong>Meaning:</strong>
  <%= @maxim.meaning %>
</p>

<p>
  <strong>Person:</strong>
  <%= @maxim.person %>
</p>

<%= link_to 'Edit', edit_maxim_path(@maxim) %> |
<%= link_to 'Back', maxims_path %>