config/routes.rb
Rails.application.routes.draw do

get 'admin' => "admin_home#top"

  resources :exhibitions
  resources :schools
  resources :articles
  resources :maxims
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get "/" => "home#top"


end

app/models/school.rb
class School < ApplicationRecord
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :category, :ward, :address, :station, :day_of_week, :teacher_name, :teacher_profile, :fee)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_with(model: school, local: true) do |form| %>
  <% if school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :school_name %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :school_category %>
  </div>

  <div class="field">
    <%= form.label :ward %>
    <%= form.text_field :ward, id: :school_ward %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :school_address %>
  </div>

  <div class="field">
    <%= form.label :station %>
    <%= form.text_field :station, id: :school_station %>
  </div>

  <div class="field">
    <%= form.label :day_of_week %>
    <%= form.text_field :day_of_week, id: :school_day_of_week %>
  </div>

  <div class="field">
    <%= form.label :teacher_name %>
    <%= form.text_field :teacher_name, id: :school_teacher_name %>
  </div>

  <div class="field">
    <%= form.label :teacher_profile %>
    <%= form.text_area :teacher_profile, id: :school_teacher_profile %>
  </div>

  <div class="field">
    <%= form.label :fee %>
    <%= form.number_field :fee, id: :school_fee %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Ward</th>
      <th>Address</th>
      <th>Station</th>
      <th>Day of week</th>
      <th>Teacher name</th>
      <th>Teacher profile</th>
      <th>Fee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.name %></td>
        <td><%= school.category %></td>
        <td><%= school.ward %></td>
        <td><%= school.address %></td>
        <td><%= school.station %></td>
        <td><%= school.day_of_week %></td>
        <td><%= school.teacher_name %></td>
        <td><%= school.teacher_profile %></td>
        <td><%= school.fee %></td>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @school.category %>
</p>

<p>
  <strong>Ward:</strong>
  <%= @school.ward %>
</p>

<p>
  <strong>Address:</strong>
  <%= @school.address %>
</p>

<p>
  <strong>Station:</strong>
  <%= @school.station %>
</p>

<p>
  <strong>Day of week:</strong>
  <%= @school.day_of_week %>
</p>

<p>
  <strong>Teacher name:</strong>
  <%= @school.teacher_name %>
</p>

<p>
  <strong>Teacher profile:</strong>
  <%= @school.teacher_profile %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @school.fee %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>